[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["grid_gym"]

[project]
name = "grid_gym"
version = "0.0.1"
dependencies = [
  "gymnasium",
  "matplotlib>=3.7.1",
  "numpy>=1.21.0",
  "pygame>=2.1.3",
  "pre-commit",
]
